### PR TITLE
Document inclusive ranges.

### PR DESCRIPTION
**Pull request by alercah**
This provides documentation for rust-lang/rust#28237.

### CODE REVIEW

**Comment by steveklabnik** [comment]
These just landed in stable. Let's retry travis!

**Comment by alercah** [comment]
Looks like it's failing; is it running stable and/or not up to date with the nightly?

**Comment by marioidival** [comment]
@alercah Rust stable https://github.com/rust-lang/rust-by-example/blob/master/.travis.yml#L5

**Comment by frewsxcv** [comment]
seems like we'll need to do one of three:

* wait until it lands in stable rust, then merge
* ...or update travis to use nightly rust
* ...or update the code block to be `rust,ignore`

**Comment by frewsxcv** [comment]
actually, since rust-by-example now rides the docs release train, _seems_ like it should be safe to do the second option and turn on nightly rust for travis ci

**Comment by steveklabnik** [comment]
Yes, that's what we should do. Run with nightly but check there aren't any feature gates.

**Pull request merged**
