### PR TITLE
Remove ", that\n> "

### PR DESCRIPTION
**Pull request by kraai**
I'm not sure that this is the correct solution, but I'm pretty sure it should be changed in some way.

### CODE REVIEW

**Comment by kraai** [comment]
The same text also appears in at least "10.4 super and self".  I'll look into updating that as well.

**Comment by mdinger** [comment]
Did you run this after changing it? This change results in:

```text
called `my::indirect_access()`called `my::private_function()`
```
instead of 

```text
called `my::indirect_access()` that
> called `my::private_function()`
```

The intent is to show that `indirect_access()` is indirectly accessing `private_function()`. `that` suggests something will be following and `>` is used to distinguish it from the other *self contained* lines while maintaining almost the exact same format. These two lines go together while still being distinguishable.

What specific problem are you trying to solve?

**Comment by kraai** [comment]
Oops, I hadn't run the program and didn't realize that it was supposed to be that way.  Thanks for the explanation.

**Comment by mdinger** [comment]
Sure

**Pull request closed without merging**
