### PR TITLE
Clarify `Into` description

### PR DESCRIPTION
**Pull request by crajcan**
https://github.com/rust-lang/rust-by-example/issues/1149

### CODE REVIEW

**Comment by marioidival** [comment]
@crajcan Oops, I'm sorry for the long delay.

I thought your change was good but to complement what we already had.

You can take your paragraph and replace it only with the first paragraph of the code snippet, keeping the second paragraph?

**Comment by crajcan** [comment]
> @crajcan Oops, I'm sorry for the long delay.
> 
> I thought your change was good but to complement what we already had.
> 
> You can take your paragraph and replace it only with the first paragraph of the code snippet, keeping the second paragraph?

@marioidival, thanks for taking the time to review.

Now that I look at this closer, it is apparent you are right about keeping the second paragraph. I have made another commit for you to review.

There is another sentence at the top of this page that I think has mislead some users (see issue  #1149):

```If you are able to convert type A from type B, then it
should be easy to believe that we should be able to convert type B to type A.```

And perhaps a sentence in the API documentation that has done the same:

https://github.com/rust-lang/rust/blob/d19a359444295bab01de7ff44a9d72302e573bc9/src/libcore/convert.rs#L203

Since both from and into have the same type signatures, I think what is important to highlight in Rust By Example is that:

1. The `From` implementation should be preferred
2. `Into` is implemented on the destination type, while `From` is implemented on the origin type.
3. `Into` must be implemented instead of `From` when both types are not defined by the current crate.

Perhaps these differences are be too subtle to warrant description in RBE. I'll try to make another small PR or two, and maybe you can review?

**Comment by marioidival** [comment]
@crajcan of course!

**Comment by marioidival** [comment]
@crajcan you can make it on this PR

**Comment by marioidival** [comment]
@crajcan ?

**Comment by marioidival** [comment]
@crajcan i can close this PR?

**Pull request closed without merging**
