### PR TITLE
Add pub(restricted) example

### PR DESCRIPTION
**Pull request by cramertj**
See https://github.com/rust-lang/rust/issues/32409
cc @steveklabnik

### CODE REVIEW

**Comment by cramertj** [comment]
(Travis is obviously going to fail since the feature isn't stable yet.)

**Comment by steveklabnik** [comment]
Yup! RBE deploys to master always, so we'll have to wait until the release to merge.

**Comment by cramertj** [comment]
To add:
- path in pub(in path) item must be some parent module of the item.
- pub(super) and pub(self) are shortcuts for pub(in super) and pub(in self) respectively
- pub(self) is the same thing as private

**Comment by steveklabnik** [comment]
We'll be able to merge this Thursday; it now is green on beta 🎊

**Comment by steveklabnik** [comment]
Woo!

**Pull request merged**
