### PR TITLE
Add missing attribute example

### PR DESCRIPTION
**Pull request by gingermusketeer**

### CODE REVIEW

**Comment by steveklabnik** [comment]
I'm sorry, what is this fixing? I think I've missed something.

**Comment by gingermusketeer** [comment]
`custom.out` did not exist so it ended up looking like

screen shot 2015-01-12 at 1 14 15 pm

**Comment by steveklabnik** [comment]
Gotcha. The right way to make this change would be to create a file for `custom.out`. This system is used so that it gets updated automatically... would you like to take a crack at that?

**Comment by gingermusketeer** [comment]
Ah right. I changed it to match the section below "With the custom `cfg` flag:". Should i change that to be separate file as well?

**Comment by gingermusketeer** [comment]
@steveklabnik I got to the bottom of the issue. It was a wider problem with all `{example.out}` replacements. When the show formatter is used on a string it surrounds it in quotes. This meant it was trying to replace `{"example".out}` instead of `{example.out}`

**Comment by steveklabnik** [comment]
Ahh awesome. Thanks!

**Pull request merged**
