### PR TITLE
Update cargo lock

### PR DESCRIPTION
**Pull request by mdinger**
travis is failing. This passes `make test` on my computer. I'm assuming it wasn't a travis fluke.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks! Yeah it's been failing for a day or two, I had this on my list, but you beat me to it! :heart: :confetti_ball:

**Comment by mdinger** [comment]
Ah. I don't get emails so I either have to just notice it or check the rbe site

**Comment by steveklabnik** [comment]
do you want to get put on the email list? It's just a setting in cargo.toml

**Comment by htunk** [comment]
ju

**Comment by mdinger** [comment]
Just add my email to the authors list and I'll get notifications? I know how to get emails from travis for my fork of this repo but not this repo.

**Comment by steveklabnik** [comment]
http://docs.travis-ci.com/user/notifications/#Email-notifications

You'd change this config to email the both of us

**Pull request merged**
