### PR TITLE
Added missing write(true) option. Fixes issue #765.

### PR DESCRIPTION
**Pull request by realcr**

### CODE REVIEW

**Comment by mdinger** [comment]
Looks good to me. Is inline with [openoptions](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html) docs

**Comment by mdinger** [comment]
Though, it should probably mirror the docs main example and be `read` as well:

```rust
use std::fs::OpenOptions;

let file = OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .open("foo.txt");
```

**Comment by realcr** [comment]
@mdinger: The example shows how to implement touch, which doesn't need the `.read` option, so maybe we shouldn't add it here. What do you think?

**Comment by mdinger** [comment]
Isn't the intent of touch to make a new file which is readable?

**Comment by realcr** [comment]
Maybe the person who originally wrote this should comment on this.
I think that the touch function should be some kind of imitation of the Unix touch command.

For example, see here: http://www.linfo.org/touch.html

>  The touch command is the easiest way to create new, empty files. It is also used to change the timestamps (i.e., dates and times of the most recent access and modification) on existing files and directories. 

To me it doesn't sound like touch should be able to read from the file.

**Comment by steveklabnik** [comment]
Yup, I agree @realcr . Thanks!

**Comment by mdinger** [comment]
Oooooh, I was thinking read/write was going to configure the OS read/write permissions, not if the operation could just read the file. Silly me.

**Pull request merged**
