### PR TITLE
Introduction: remove duplicate [rust] call

### PR DESCRIPTION
**Pull request by sjef**
Possible fix for issue #465

### CODE REVIEW

**Comment by mdinger** [comment]
That won't work. `[a][b]` is deferring a link to later in the file. Like here, the link would use the text `Rust` and use the `rust` link at the bottom of the page. This just means that google isn't parsing the markdown. This markdown:

```markdown
[Rust][rust] is a programming language with a focus on

[rust]: http://www.rust-lang.org/
```

Results in this:

[Rust][rust] is a programming language with a focus on

[rust]: http://www.rust-lang.org/

**Comment by mdinger** [comment]
Markdown referencing conventions are listed [here](https://github.com/steveklabnik/rfcs/blob/api_comment_conventions/text/0000-api-comment-conventions.md#using-markdown)

**Comment by sjef** [comment]
I see. 

The issue is then completely in the hands of the search engine provider?

**Comment by mdinger** [comment]
Yeah. That's why Bing and Duckduckgo look correct; they are doing more comprehensive formatting of search results. Google has typically been pretty minimalistic about search results and may be part of it's popularity.

A more correct approach would be to request that Google parse the markdown in the search results though I don't know if Google has that option or where it would be. I just looked and couldn't find it.

[Yahoo](http://search.yahoo.com/search?p=rust%20by%20example) also get's it correct but Yahoo has typically been pretty heavy-handed with search styles so that's not surprising.

**Comment by mdinger** [comment]
If Google has an option though or something to configure search results, it would be good to fix this. This isn't particularly pretty.

**Comment by sjef** [comment]
I don't know how to get in touch with Google regarding issues like this. 

One fix from our side could be to refer/link to rust-lang.org at the second mention of "Rust". This is of course suboptimal.

**Comment by mdinger** [comment]
I think it's probably buried somewhere in [here](https://support.google.com/webmasters/topic/4598337?hl=en&ref_topic=3309300) though I don't have time to find it now. You've probably got to annotate the webpage so it's labeled as Markdown somehow.

I doubt they'll go for changing the formatting. I'd explore annotation. It's probably possible.

**Comment by steveklabnik** [comment]
Since this isn't going to be an actual fix, I'm going to give it a close.

**Pull request closed without merging**
