### PR TITLE
Fix broken examples

### PR DESCRIPTION
**Pull request by lstat**

### CODE REVIEW

**Comment by lstat** [comment]
So this didn't fix the broken build, but what I did do was fix `make test`. Will that be enough to be accepted to merge?

**Comment by lstat** [comment]
Actually `simd_add` is still broken broken, I need to update my local rust version.

**Comment by steveklabnik** [comment]
Yeah, we still need regex macros

**Comment by lstat** [comment]
Ah ok, sorry just getting up to speed. Is someone already tasked with fixing the build?

Is there anything I can do to help?

**Comment by steveklabnik** [comment]
It's all good!https://github.com/rust-lang/rust-by-example/pull/361 is related, and @GBGamer has been making lots of great PRs that I haven't had a chance to review :(

**Comment by lstat** [comment]
Ok great, thanks for taking the time to explain, apologies for not reading the PR's more throughly. Closing this in favour of existing #361. Will revisit if needed once the build is fixed.

**Comment by steveklabnik** [comment]
It's all good! I'd rather have more PRs than less, even if my reviewing skills are poor

**Comment by GBGamer** [comment]
@steveklabnik Do you need help reviewing? I'd be fine with reviewing any PRs that aren't my own. You seem to be very busy :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
