### PR TITLE
Add example to partial struct's copies

### LINKED ISSUE #207: Struct: Add example about "partial" copies/clones
Something like this, but nicer:

``` rust
#[deriving(Show)]
struct Triplet {
    first: uint,
    second: uint,
    third: uint,
}

fn main() {
    let t = Triplet { first: 0, second: 1, third: 2 };
    let u = Triplet { first: 3, .. t };

    println!("{}", t);
    println!("{}", u);
}
```

Output:

```
Triplet { first: 0, second: 1, third: 2 }
Triplet { first: 3, second: 1, third: 2 }
```

Probably should be in the `struct` chapter.

### PR DESCRIPTION
**Pull request by marioidival**
fixes #207

### CODE REVIEW

**Comment by marioidival** [comment]
@QuietMisdreavus you have permissions to rebuild this in travis?

**Comment by marioidival** [comment]
@projektir @QuietMisdreavus 
--

It’s often useful to create a new instance of a struct that uses most of an old instance’s values, but changes some. We do this using struct update syntax.


how we create a new `Triplet` instance in `t` without the update syntax. We set new values for `first` and `second`, but otherwise use the same values from `u` that we created.

**Comment by QuietMisdreavus** [comment]
This is probably better served by adding a few lines to the existing example in this chapter, rather than spotlighting it on its own. Right after the `println!("point coordinates:")` add a few lines like this:

```rust
// Make a new point by using struct update syntax to use the fields of our other one
let new_point = Point { x: 0.1, ..point };

// `new_point.y` will be the same as `point.y` because we used that field from `point`
println!("second point: ({}, {})", new_point.x, new_point.y);
```

**Comment by marioidival** [comment]
@QuietMisdreavus @projektir updated!

**Pull request merged**
