### PR TITLE
into_iter() yielding i32 instead of &i32

### PR DESCRIPTION
**Pull request by velaia**
as noted in #1460 by @2moe

### CODE REVIEW

**Comment by velaia** [comment]
~/g/R/R/t/debug (master|✚1) $ rustc --version
rustc 1.56.0 (09c42c458 2021-10-18)

**Comment by marioidival** [comment]
@velaia this fails

**Comment by velaia** [comment]
@marioidival I'll look into it (after checking the contribution guidelines). Thanks.

**Comment by velaia** [comment]
It has probably got to do with the edition= "2021" in my Cargo.toml

I receive this warning:

> ~/g/R/RustByExample (master|✚1…) $ rustc src/main.rs
warning: this method call resolves to `<&[T; N] as IntoIterator>::into_iter` (due to backwards compatibility), but will resolve to <[T; N] as IntoIterator>::into_iter in Rust 2021.
  --> src/main.rs:16:40
   |
16 |     println!("2 in array2: {}", array2.into_iter().any(|&x| x == 2));
   |                                        ^^^^^^^^^
   |
   = note: `#[warn(array_into_iter)]` on by default
   = warning: this changes meaning in Rust 2021
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/IntoIterator-for-arrays.html>
help: use `.iter()` instead of `.into_iter()` to avoid ambiguity
   |
16 |     println!("2 in array2: {}", array2.iter().any(|&x| x == 2));
   |                                        ~~~~
help: or use `IntoIterator::into_iter(..)` instead of `.into_iter()` to explicitly iterate by value
   |
16 |     println!("2 in array2: {}", IntoIterator::into_iter(array2).any(|&x| x == 2));
   |                                 ++++++++++++++++++++++++      ~

> warning: 1 warning emitted

**Comment by velaia** [comment]
@marioidival I think I should close this PR if the edition of the book stays at 2018. Any intention to update edition to 2021 anytime soon?

**Pull request closed without merging**
