### PR TITLE
Change int and uint to new types

### LINKED ISSUE #380: Several examples give warnings about deprecated 'i' and 'u' suffix
The following pages need to have updated suffixes:

* http://rustbyexample.com/print.html
* http://rustbyexample.com/literals.html
* http://rustbyexample.com/variables.html
* http://rustbyexample.com/variables/mut.html
* http://rustbyexample.com/variables/scope.html
* http://rustbyexample.com/variables/declare.html
* http://rustbyexample.com/type.html
* http://rustbyexample.com/type/literals.html

And possibly more. Would fix myself but don't know what the desired fix is. (`is` and `us`?)

The last page I checked was http://rustbyexample.com/type/inference.html, which is broken but not because of suffixes. Starting to think maybe there's an issue with the Javascript Rust... thing.

Additionally, http://rustbyexample.com/type/literals.html should be updated to explain the new suffixes.

UPDATE YET AGAIN: actually pretty much all the examples I've checked so far are broken. And some of them for other reasons (e.g. http://rustbyexample.com/variables.html breaks because apparently `()` doesn't play well with `println!`..?) If this is already known sorry for creating more noise in your issue tracker!!

### PR DESCRIPTION
**Pull request by gingermusketeer**
Makes a few smaller changes so that `make test` passes

Closes #380

### CODE REVIEW

**Comment by GBGamer** [comment]
The issue with this PR is that we don't want `isize` as the default (hence the renaming). We want, for most things, to use i32/u32, and, in cases where it might be necessary to use 64 bits, i64/u64. We only want to use isize in places where we create vectors, and such like that.

**Comment by gingermusketeer** [comment]
@GBGamer I didn't see it mentioned that the renaming was to discourage its usage. My understanding is that it was changed to better reflect the consequences of using it.

I am happy to change it though. I do think that `i32`/`u32` etc would be a better choice

**Comment by steveklabnik** [comment]
We want:

1. To not use suffixes where they're not needed.
2. To prefer i32/u32 for most things
3. to use isize/usize when dealing with lengths.

**Comment by gingermusketeer** [comment]
@steveklabnik Just spotted @GBGamer's PR with the same fixes. Happy for you to close this and use #381 instead

**Comment by steveklabnik** [comment]
Okay! That's what I've done. Thank you!

**Pull request closed without merging**
