### PR TITLE
Fixes #890

### LINKED ISSUE #890: Mention that crate_type attribute is ignored when using Cargo
<https://rustbyexample.com/attribute/crate.html> is the first search hit when I look for information on the `crate_type` attribute. Unfortunately, that site fails to mention that the attribute has *no effect whatsoever* when using Cargo.

Given that this means the attribute is hardly ever useful, I think this is worth mentioning.

### PR DESCRIPTION
**Pull request by outkaj**
How does this look as an improvement to the issue mentioned in #890? Thanks a lot!

### CODE REVIEW

**Comment by mark-i-m** [comment]
Is the same true for `crate_name`? If so, it might be worth mentioning too.

**Comment by outkaj** [comment]
[It looks to me like the same is not true for `crate_name`](https://dumindu.gitbooks.io/learning-rust/content/04.%20cargo,_crates_and_basic_project_structure.html), but could someone else confirm? Thanks for the question @mark-i-m

**Comment by steveklabnik** [comment]
I believe it's true, yes. Would you mind adding it as well? :)

**Comment by outkaj** [comment]
Not at all!

**Comment by steveklabnik** [comment]
This is great, thanks! After travis is green, I'll merge. Should be fine :)

**Pull request merged**
