### PR TITLE
Make deploy.sh script executable

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Is there a specific reason to do this?

**Comment by frewsxcv** [comment]
All their other shell scripts that are in root are executable. Doesn't make a difference to me whether this gets merged or not, I just wanted to point out the inconsistency

**Comment by steveklabnik** [comment]
Ahh, that's just a difference between me and the previous maintainer, I guess. Might as well make it consistent.

**Comment by steveklabnik** [comment]
Thanks!

**Pull request merged**
