### PR TITLE
Update rust

### PR DESCRIPTION
**Pull request by mdinger**
Fixes https://github.com/rust-lang/rust-by-example/issues/534

### CODE REVIEW

**Comment by mdinger** [comment]
Repushed to get travis to retry

**Comment by mdinger** [comment]
@steveklabnik should rbe follow nightlies or beta? If nightlies, `rustup` has to be updated. If beta, `#![feature(...)]`s all have to be pruned.

**Comment by steveklabnik** [comment]
We should just stick with nightly for this moment

**Comment by mdinger** [comment]
okay. I'll make the changes.

**Comment by mdinger** [comment]
Fixed and passes travis

**Comment by mdinger** [comment]
Updated. This now fixes https://github.com/rust-lang/rust-by-example/issues/534

**Comment by steveklabnik** [comment]
Thanks!

**Pull request merged**
