### PR TITLE
Add example struct field init shorthand

### PR DESCRIPTION
**Pull request by hngnaig**

### CODE REVIEW

**Comment by Havvy** [comment]
Travis fails on stable and beta where field init shorthand syntax doesn't exist. It succeeds on nightly where it does. I'm presuming this patch will sit here until a release that has field init shorthand syntax in stable?

**Comment by steveklabnik** [comment]
Yes.

**Comment by steveklabnik** [comment]
@hngnaig this syntax is now stable, can you remove the `#![feature]` stuff and then we can merge? Thanks!

**Comment by steveklabnik** [comment]
I've made the change. Thanks!

**Pull request merged**
