### PR TITLE
Fix borrow so it fails in 2018 edition Fixes #1141

### LINKED ISSUE #1141: 2018 borrow checker
https://doc.rust-lang.org/rust-by-example/scope/borrow.html shows an example that supposedly does not work, but actually does work with Rust 2018:
```rust
{
        // Take a reference to the data contained inside the box
        let _ref_to_i32: &i32 = &boxed_i32;

        // Error!
        // Can't destroy `boxed_i32` while the inner value is borrowed.
        eat_box_i32(boxed_i32);
        // FIXME ^ Comment out this line

        // `_ref_to_i32` goes out of scope and is no longer borrowed.
    }
```

### PR DESCRIPTION
**Pull request by gurgalex**
Fix #1152

### CODE REVIEW

**Comment by frewsxcv** [comment]
this causes a different error than the one we want

with rust 2015, the error is:

```
error[E0505]: cannot move out of `boxed_i32` because it is borrowed
  --> src/main.rs:27:21
   |
23 |         let _ref_to_i32: &i32 = &boxed_i32;
   |                                  --------- borrow of `boxed_i32` occurs here
...
27 |         eat_box_i32(boxed_i32);
   |                     ^^^^^^^^^ move out of `boxed_i32` occurs here
```

with these changes, the error is now:

```
error[E0382]: use of moved value: `boxed_i32`
  --> src/main.rs:30:34
   |
27 |         eat_box_i32(boxed_i32);
   |                     --------- value moved here
...
30 |         let _ref_to_i32: &i32 = &boxed_i32;
   |                                  ^^^^^^^^^ value used here after move
   |
   = note: move occurs because `boxed_i32` has type `std::boxed::Box<i32>`, which does not implement the `Copy` trait
```

**Comment by marioidival** [comment]
@gurgalex ^

**Comment by gurgalex** [comment]
Ah, whoops.

I'll think about this again today.

**Comment by gurgalex** [comment]
@frewsxcv 
The error messages are now the same as before.

**Comment by marioidival** [comment]
@gurgalex thank you!

**Pull request merged**
