### PR TITLE
refine wording

### PR DESCRIPTION
**Pull request by bmusin**
"lambda expression" is more precise and technically correct term than simply "lambda"

### CODE REVIEW

**Comment by marioidival** [comment]
@QuietMisdreavus LGTM

**Comment by QuietMisdreavus** [comment]
Hmm. While it's more accurate to call them "lambda expressions", it would still be worth noting that they're often just called "lambdas" informally. Maybe like this?

> Closures in Rust, also called lambda expressions or just lambdas, \[...\]

**Comment by projektir** [comment]
@bmusin 
Hey, are you planning to update this

**Comment by bmusin** [comment]
Thanks, for reminding. Updated.

**Pull request merged**
