### PR TITLE
Rename unit conversion

### PR DESCRIPTION
**Pull request by joemphilips**
the title of section 12.8.1 is `unit conversion` but there is no conversion really so I suppose `unit clarification` is better

### CODE REVIEW

**Comment by steveklabnik** [comment]
@joemphilips it seems like there's a lot of unrelated commits in here; maybe double check what you did?

**Comment by joemphilips** [comment]
excuse me ...

**Comment by steveklabnik** [comment]
No worries!

Uh, one last thing: it seems like I'm the author of the commit somehow. can you fix that as well? Happy to merge after.

**Comment by joemphilips** [comment]
Hmmm........ wonder why that happend.
now it's fixed.

**Pull request merged**
