### PR TITLE
Updating borrow/borrow: adding box_syntax feature, changing int to isize

### PR DESCRIPTION
**Pull request by jamiltron**

### CODE REVIEW

**Comment by steveklabnik** [comment]
I like this patch, but two things:

1. We shouldn't use `box_syntax`, we should stick to no feature gates where possible.
2. This should be `i32`, not `isize`.

Would you mind making those changes? And thank you!

**Comment by jamiltron** [comment]
Will do!

**Comment by jamiltron** [comment]
Updated. Should the other box_syntax features be removed? It appears that the only place where its really useful is in the Box, stack and heap example.

**Comment by steveklabnik** [comment]
Thank you!

**Pull request merged**
