### PR TITLE
broken long comments in src/types/cast.md to several shortones

### PR DESCRIPTION
**Pull request by gpk2000**
I needed to scroll horizontally to the end to read the entire comment line. So I split it into several shorter ones (did not add anything).

### CODE REVIEW

**Comment by gpk2000** [comment]
Umm idk what happened, but why is this conflicting files occur now not earlier 🤔

**Review by marioidival — APPROVED** [review]

**Comment by marioidival** [comment]
@gpk2000 you need resolve the conflicts

**Comment by gpk2000** [comment]
Sure just a moment. 🙂

**Comment by marioidival** [comment]
@gpk2000 thank you

**Pull request merged**
